import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { workouts, type Workout } from './db'
import { createCrunchDetector, createPushUpDetector } from './poseDetector'
import PoseOverlay from './PoseOverlay'
import SocialHub from './SocialHub'
import { social } from './social'
import type { Landmark } from './pushUpCounter'

type View = 'home'|'workout'|'history'|'social'; type Exercise='pushups'|'crunches'
type Debug={mode:'SETUP'|'READY';state:string;elbowAngle?:number|null;torsoAngle?:number|null;visibility:number;reps:number}
const day=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)

export default function App(){
  const [view,setView]=useState<View>('home'),[exercise,setExercise]=useState<Exercise>('pushups'),[goal,setGoal]=useState(20),[reps,setReps]=useState(0),[history,setHistory]=useState<Workout[]>([]),[feedback,setFeedback]=useState('Colócate dentro de la guía'),[debug,setDebug]=useState<Debug>({mode:'SETUP',state:'UP',visibility:0,reps:0}),[landmarks,setLandmarks]=useState<Landmark[]|null>(null),[stream,setStream]=useState<MediaStream|null>(null),[facing,setFacing]=useState<'user'|'environment'>('user'),[error,setError]=useState('')
  const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),requestRef=useRef(0),repsRef=useRef(0),saving=useRef(false),startedAt=useRef(0)
  const push=useMemo(createPushUpDetector,[]),crunch=useMemo(createCrunchDetector,[])
  const refresh=async()=>setHistory((await workouts.all()).sort((a,b)=>b.date.localeCompare(a.date)))
  useEffect(()=>{void refresh()},[])
  const stop=useCallback(()=>{requestRef.current++;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setStream(null);push.stop();crunch.stop()},[push,crunch])
  const requestCamera=useCallback(async(next:'user'|'environment')=>{stop();const id=requestRef.current;try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{exact:next},width:{ideal:1280},height:{ideal:720}},audio:false});if(id!==requestRef.current){s.getTracks().forEach(t=>t.stop());return}streamRef.current=s;setFacing(next);setStream(s)}catch{setError('No se pudo acceder a esta cámara.')}},[stop])
  const say=(text:string)=>{if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}
  const finish=useCallback(async(finalReps=repsRef.current)=>{if(saving.current)return;saving.current=true;stop();const durationSeconds=Math.max(0,Math.round((Date.now()-startedAt.current)/1000));if(finalReps>0){const xp=finalReps>=goal?50:Math.max(10,finalReps);await workouts.add({date:day(),reps:finalReps,goal,xp,exercise,durationSeconds});await social.recordWorkout(exercise,finalReps,durationSeconds).catch(()=>undefined);await refresh()}setView('home');saving.current=false},[stop,goal,exercise])
  const addRep=useCallback(()=>{if(repsRef.current>=goal)return;const next=++repsRef.current;setReps(next);if(next%5===0||next===goal)say(next===goal?'Serie completada':`${next}`);if(next>=goal){setFeedback('Serie completada');window.setTimeout(()=>void finish(next),900)}},[goal,finish])
  useEffect(()=>{if(exercise==='pushups'){push.onRep(addRep);push.onFeedback(v=>setFeedback(v));push.onPose(setLandmarks);push.onDebug(v=>setDebug(v));return()=>push.stop()}crunch.onRep(addRep);crunch.onFeedback(v=>setFeedback(v));crunch.onPose(setLandmarks);crunch.onDebug(v=>setDebug(v));return()=>crunch.stop()},[exercise,push,crunch,addRep])
  useEffect(()=>{if(view!=='workout'||!stream||!videoRef.current)return;const video=videoRef.current,detector=exercise==='pushups'?push:crunch;let cancelled=false;video.srcObject=stream;video.play().then(()=>cancelled?undefined:detector.start(video)).catch(()=>setError('No se pudo iniciar la detección.'));return()=>{cancelled=true;detector.stop()}},[view,stream,exercise,push,crunch])
  useEffect(()=>()=>stop(),[stop])
  const start=async()=>{saving.current=false;startedAt.current=Date.now();repsRef.current=0;setReps(0);setLandmarks(null);setDebug({mode:'SETUP',state:'UP',visibility:0,reps:0});setFeedback('Colócate dentro de la guía');setError('');setView('workout');await requestCamera(facing)}
  const totalXp=history.reduce((s,w)=>s+w.xp,0)
  if(view==='social')return <SocialHub onClose={()=>setView('home')}/>
  if(view==='workout')return <main className="workout"><button className="back" onClick={()=>void finish()}>×</button><div className="camera"><video ref={videoRef} className={facing==='user'?'mirrored':''} muted playsInline/><svg className={`setup-guide ${exercise==='crunches'?'crunch-guide':''}${debug.mode==='READY'?' ready':''}${facing==='user'?' mirrored':''}`} viewBox="0 0 100 100" aria-label="Guía de posición">{exercise==='pushups'?<><circle cx="20" cy="38" r="5"/><path d="M25 42 L48 50 L74 52 M29 46 L16 62 L7 70 M48 50 L61 67 L82 72"/></>:<><circle cx="17" cy="67" r="5"/><path d="M22 67 C33 67 43 69 55 72 L66 72 M34 69 L40 57 M66 72 L79 54 L92 72 M66 73 L78 86 L94 86"/><circle cx="79" cy="54" r="2"/><circle cx="92" cy="72" r="2"/><circle cx="94" cy="86" r="2"/></>}</svg><PoseOverlay landmarks={landmarks} mirrored={facing==='user'}/><button className="switch-camera" onClick={()=>void requestCamera(facing==='user'?'environment':'user')}>↺ <span>{facing==='user'?'Frontal':'Trasera'}</span></button><div className="counter overlay-counter">{reps}<span> / {goal}</span></div><div className="camera-label">{exercise==='pushups'?'PUSH-UPS':'CRUNCHES'} · {debug.mode}</div></div><div className="debug-panel"><b>DEBUG</b><span>Modo: {debug.mode}</span><span>Estado: {debug.state}</span><span>Ángulo: {debug.elbowAngle??debug.torsoAngle??'—'}°</span><span>Visibilidad: {debug.visibility}%</span><span>Reps: {reps}</span></div><div className="feedback">{feedback}</div>{error&&<p className="notice">{error}</p>}<div className="progress"><i style={{width:`${Math.min(100,reps/goal*100)}%`}}/></div><div className="controls"><button className="round" onClick={()=>{repsRef.current=Math.max(0,repsRef.current-1);setReps(repsRef.current)}}>−</button><button className="rep" onClick={addRep}>+1</button><button className="round" onClick={()=>void finish()}>✓</button></div></main>
  if(view==='history')return <main><button className="link" onClick={()=>setView('home')}>‹ Inicio</button><h2>Historial</h2>{history.map(w=><article className="history" key={w.id}><b>{w.exercise==='crunches'?'Crunches':'Push-ups'}</b><span>{w.reps} reps · +{w.xp} XP</span></article>)}</main>
  return <main><header><div><p className="brand">FIT STREAK</p><h1>Hola, atleta.</h1></div><button className="link" onClick={()=>setView('social')}>Perfil</button></header><section className="xp"><span>NIVEL 1</span><strong>{totalXp} XP</strong><div><i style={{width:`${totalXp%100}%`}}/></div></section><p className="eyebrow">ENTRENAMIENTO DE HOY</p><section className="card"><div className="goals"><button className={exercise==='pushups'?'selected':''} onClick={()=>setExercise('pushups')}>Push-ups</button><button className={exercise==='crunches'?'selected':''} onClick={()=>setExercise('crunches')}>Crunches</button></div><h2>{exercise==='pushups'?'Push-ups':'Crunches'}<br/><span>{exercise==='pushups'?'Despechadas':'Abdominales'}</span></h2><label>Objetivo</label><div className="goals">{[10,20,30,40].map(n=><button className={goal===n?'selected':''} onClick={()=>setGoal(n)} key={n}>{n}</button>)}</div><button className="primary" onClick={()=>void start()}>Empezar entrenamiento <span>→</span></button></section><button className="history-button" onClick={()=>setView('history')}>Ver historial <span>›</span></button></main>
}
