import { useEffect, useState } from 'react'
import { auth } from './auth'
import { isSupabaseConfigured, supabase } from './supabase'
import { social, type Profile, type RankingRow } from './social'
import './social.css'

export default function SocialHub({ onClose }: { onClose: () => void }) {
  const [session,setSession]=useState(false),[mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState('')
  const [me,setMe]=useState<Profile|null>(null),[query,setQuery]=useState(''),[users,setUsers]=useState<Profile[]>([]),[friends,setFriends]=useState<Profile[]>([]),[ranking,setRanking]=useState<RankingRow[]>([]),[metric,setMetric]=useState<'streak'|'xp'|'week'>('streak')
  const load=async()=>{setMe(await social.me());setFriends(await social.friends());setRanking(await social.rankings(metric))}
  useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(Boolean(data.session)));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>setSession(Boolean(next)));return()=>subscription.unsubscribe()},[])
  useEffect(()=>{if(session)void load()},[session,metric])
  if(!isSupabaseConfigured)return <main><button className="link" onClick={onClose}>‹ Inicio</button><h2>Conecta Supabase</h2><p className="empty">Configura tu archivo <code>.env</code> y ejecuta la migración SQL incluida.</p></main>
  if(!session)return <main className="account-page"><button className="link back-home" onClick={onClose}>‹ Inicio</button><p className="brand">FIT STREAK</p><h1>Tu cuenta</h1><section className="card auth-form"><p className="auth-intro">{mode==='login'?'Inicia sesión para guardar tu progreso y conectar con tus amigos.':'Crea tu perfil y empieza a subir de nivel.'}</p><label>Email<input type="email" placeholder="tu@email.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" placeholder="Mínimo 6 caracteres" value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==='signup'&&<><label>Username<input placeholder="ej. axel_fit" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Nombre visible<input placeholder="Cómo te verán tus amigos" value={name} onChange={e=>setName(e.target.value)}/></label></>}<button className="primary" onClick={async()=>{const result=mode==='login'?await auth.signIn(email,password):await auth.signUp(email,password,username,name);setMessage(result.error?.message??(mode==='login'?'¡Bienvenido de vuelta!':'Revisa tu email para confirmar tu cuenta.'))}}>{mode==='login'?'Iniciar sesión':'Crear cuenta'} <span>→</span></button><div className="auth-actions"><button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Crear cuenta':'Ya tengo una cuenta'}</button>{mode==='login'&&<button className="link" onClick={async()=>{const result=await auth.resetPassword(email);setMessage(result.error?.message??'Email de recuperación enviado.')}}>¿Olvidaste tu contraseña?</button>}</div>{message&&<p className="notice">{message}</p>}</section></main>
  return <main><button className="link" onClick={onClose}>‹ Inicio</button><header><div><p className="brand">PERFIL</p><h1>{me?.display_name||me?.username}</h1></div><button className="link" onClick={()=>void auth.signOut()}>Salir</button></header>{me&&<section className="card profile-summary"><p>@{me.username}</p><h2>{me.xp_total} XP</h2><p>🔥 {me.current_streak} días · Mejor {me.best_streak}</p><p>🛡️ {me.streak_protectors} protectores · Nivel {me.level}</p></section>}<section className="card"><h3>Amigos</h3><input className="social-input" placeholder="Buscar username" value={query} onChange={async e=>{setQuery(e.target.value);setUsers(await social.search(e.target.value))}}/>{users.map(u=><p key={u.id}>@{u.username} <button className="link" onClick={()=>void social.requestFriend(u.id).then(load)}>Agregar</button></p>)}<h3>Mis amigos</h3>{friends.map(f=><p key={f.id}>@{f.username} · {f.xp_total} XP · 🔥 {f.current_streak}</p>)}</section><section className="card"><h3>Ranking</h3><div className="goals">{(['streak','xp','week']as const).map(m=><button className={metric===m?'selected':''} onClick={()=>setMetric(m)} key={m}>{m==='streak'?'Racha':m==='xp'?'XP':'Semana'}</button>)}</div>{ranking.map((r,i)=><p key={r.id}>{['🥇','🥈','🥉'][i]??`${i+1}.`} @{r.username} — {metric==='streak'?`🔥 ${r.current_streak} días`:metric==='xp'?`${r.xp_total} XP`:`${r.week_xp} XP`}</p>)}</section></main>
}
